// Plain-language explanations shown wherever a term appears with <Term>.
export const GLOSSARY = {
  'scope': 'Exactly what work you will and will not do. A clear scope stops "just one more thing" requests.',
  'scope creep': 'When the client keeps adding work without adding money.',
  'deliverables': 'The concrete things you hand over at the end, e.g. "5 web pages" or "a 2-minute video".',
  'milestone': 'A checkpoint in the project (e.g. "design approved"). You can tie part of the payment to each one.',
  'deposit': 'Money the client pays before you start, often 30-50%. It shows commitment and protects your time.',
  'net terms': 'How many days the client has to pay after receiving an invoice. "Net 14" = within 14 days.',
  'net 30': 'The client must pay within 30 days of the invoice date.',
  'payment terms': 'When and how you get paid: amounts, due dates, method, and what happens if payment is late.',
  'late fee': 'An extra charge if the client pays after the due date, e.g. 1.5% per month. It encourages paying on time.',
  'kill fee': 'A fee the client pays if they cancel the project partway, so you are paid for work already done.',
  'penalty': 'Money taken off your fee (or that you must pay) if you miss a deadline or break a rule in the contract.',
  'termination': 'How either side can end the contract early, with how much notice, and what gets paid.',
  'ip': 'Intellectual property: who owns the work you create (designs, code, writing). Ideally it transfers only after full payment.',
  'indemnity': 'A promise to cover the other side\'s costs if something you did causes them a legal problem. Keep it narrow.',
  'liability cap': 'A maximum amount you could ever owe if something goes wrong, often limited to the fee paid.',
  'non-compete': 'A clause stopping you from working for similar clients for a time. Can seriously limit your income.',
  'tax id': 'A number the tax authority gives a person or business (e.g. TIN, VAT number, EIN). Some clients need it on invoices.',
  'vat': 'Value-added tax: a sales tax added to the invoice in many countries. Only charge it if you are registered for it.',
  'counter-offer': 'Your reply to an offer with different terms, e.g. a higher price or a deposit.',
  'anchor': 'The first number mentioned in a negotiation. It pulls the final price toward it, so anchor thoughtfully.',
  'walk-away point': 'The lowest deal you will accept. Decide it before talking so you don\'t agree to something you regret.',
  'recurring invoice': 'An invoice sent on a schedule (e.g. monthly) for ongoing work like a retainer.',
  'retainer': 'A regular fee the client pays to reserve your time each month.',
  'due date': 'The last day the client can pay without being late.',
};
